### PR TITLE
Instruments panel

### PR DESCRIPTION
**Pull request by Repuler**
OwO how do you like my code sEnPaiiiiii

### CODE REVIEW

**Comment by brienatalie** [comment]
looks good

**Comment by Repuler** [comment]
hot

**Comment by Repuler** [comment]
this code is bussin

**Review by brienatalie — APPROVED** [review]
looks ### _sexyagopeoegegsegegferhertherth**wrthwrrthwthhwrthwrthwrt**_

**Comment by Repuler** [comment]
looks like ass

**Pull request merged**
